name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
          scope: '@svan-garaaz'
      - run: npm install --force
      - run: npm publish --non-interactive --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
